version: "3.8"

services:
  mongo_db1:
    container_name: mongo_db1
    image: mongo
    restart:  always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INTIDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    links:
      - mongo_db2
      - mongo_db3
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo_db2:
    container_name: mongo_db2
    image: mongo
    restart:  always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INTIDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27018:27017
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - mongors-network
    links:
      - mongo_db1
      - mongo_db3
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo_db3:
    container_name: mongo_db3
    image: mongo
    restart:  always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INTIDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27019:27017
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - mongors-network
    links:
      - mongo_db1
      - mongo_db2
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  app:
    depends_on:
      - mongo_db
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{"spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - mongors-network

volumes:
  ~/mongors/data1:
  ~/mongors/data2:
  ~/mongors/data3:
  .m2:

networks:
  mongors-network:
    driver: bridge

